#Definicao do fluxo de trabalho
name: CRUD usuários em Java - Deploy Ec2 

# Especifica que o workflow será acionado apenas quando 
# houver um push na branch "master"
on:
  push:
    branches: [ "master" ]

#Definicao dos jobs do workflow

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest # Definicao do ambiente
    environment: #Define a configuração de ambiente para este job
      name: AWS

    steps:
    - uses: actions/checkout@v3 # Action do proprio GitHub para clonar o repositório.
    - name: Compile
      run: mvn clean package # Comando que será executado neste passo, responsável por compilar o projeto Java usando o Maven e gerar o pacote.

    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0 #Action para realizar o deploy de contêineres Docker em instâncias EC2.
      with:
        checkout: false
        aws_access_key_id: ${{secrets.AKIAW3MEELUQ5F6YF2V3}} # Define a chave de acesso da AWS para autenticação, armazenada nos secrets do repositório.
        aws_secret_access_key: ${{secrets.gn6ueG4TNBuH6Ymn2hNG56ytB0QQG0vZJfGArPqC}} #Define a chave secreta de acesso da AWS para autenticação, armazenada nos secrets do repositório.
        aws_elb_app_port: 8080 #Define a porta do aplicativo que será exposta no ELB (Elastic Load Balancer) da AWS.
